package org.nci.fogedge.topology;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.Random;

/**
 * Class representing an IoT device in the fog and edge computing topology
 * Based on the paper: "An Overview of Fog Computing and Edge Computing Security and Privacy Issues"
 * (Sensors 2021, 21, 8226, https://doi.org/10.3390/s21248226)
 */
public class IoTDevice {
    private static final Logger logger = LogManager.getLogger(IoTDevice.class);
    private static final Random random = new Random();
    
    private String id;
    private WirelessType wirelessType;
    private double batteryLevel;
    private double dataGenerationRate; // KB per step
    private boolean compromised;
    private EdgeNode connectedEdgeNode;
    
    public IoTDevice(String id, WirelessType wirelessType) {
        this.id = id;
        this.wirelessType = wirelessType;
        this.batteryLevel = 100.0; // Start with full battery
        this.dataGenerationRate = 1.0 + random.nextDouble() * 9.0; // 1-10 KB per step
        this.compromised = false;
        this.connectedEdgeNode = null;
    }
    
    /**
     * Generate data from this IoT device
     * @return The generated data object
     */
    public Object generateData() {
        // Simulate data generation
        double dataSize = dataGenerationRate * (0.8 + random.nextDouble() * 0.4); // +/- 20% variation
        
        // Reduce battery based on wireless type energy consumption
        consumeBattery(wirelessType.getEnergyConsumption() * dataSize * 0.01);
        
        // Create a data object with metadata
        IoTData data = new IoTData(id, dataSize, System.currentTimeMillis(), compromised);
        
        logger.debug("Device {} generated {} KB of data using {} technology", 
                id, String.format("%.2f", dataSize), wirelessType.getName());
        
        return data;
    }
    
    /**
     * Connect this IoT device to an edge node
     * @param edgeNode The edge node to connect to
     */
    public void connectToEdgeNode(EdgeNode edgeNode) {
        this.connectedEdgeNode = edgeNode;
        logger.debug("Device {} connected to edge node {}", id, edgeNode.getId());
    }
    
    /**
     * Consume battery power for operations
     * @param amount Amount of battery to consume (percentage)
     */
    public void consumeBattery(double amount) {
        this.batteryLevel = Math.max(0, this.batteryLevel - amount);
        
        if (batteryLevel < 10.0) {
            logger.warn("Device {} battery level is low: {}%", id, String.format("%.2f", batteryLevel));
        }
    }
    
    /**
     * Mark this device as compromised (for attack simulation)
     */
    public void compromise() {
        this.compromised = true;
        logger.warn("Device {} has been compromised!", id);
    }
    
    /**
     * Restore this device to secure state
     */
    public void restore() {
        this.compromised = false;
        logger.info("Device {} has been restored to secure state", id);
    }
    
    // Getters and setters
    
    public String getId() {
        return id;
    }
    
    public WirelessType getWirelessType() {
        return wirelessType;
    }
    
    public double getBatteryLevel() {
        return batteryLevel;
    }
    
    public boolean isCompromised() {
        return compromised;
    }
    
    public EdgeNode getConnectedEdgeNode() {
        return connectedEdgeNode;
    }
    
    public double getDataGenerationRate() {
        return dataGenerationRate;
    }
    
    /**
     * Inner class representing data generated by an IoT device
     */
    public static class IoTData {
        private String deviceId;
        private double dataSize; // in KB
        private long timestamp;
        private boolean potentiallyCompromised;
        
        public IoTData(String deviceId, double dataSize, long timestamp, boolean potentiallyCompromised) {
            this.deviceId = deviceId;
            this.dataSize = dataSize;
            this.timestamp = timestamp;
            this.potentiallyCompromised = potentiallyCompromised;
        }
        
        public String getDeviceId() {
            return deviceId;
        }
        
        public double getDataSize() {
            return dataSize;
        }
        
        public long getTimestamp() {
            return timestamp;
        }
        
        public boolean isPotentiallyCompromised() {
            return potentiallyCompromised;
        }
        
        @Override
        public String toString() {
            return "IoTData{" +
                    "deviceId='" + deviceId + '\'' +
                    ", dataSize=" + String.format("%.2f", dataSize) + " KB" +
                    ", timestamp=" + timestamp +
                    ", potentiallyCompromised=" + potentiallyCompromised +
                    '}';
        }
    }
}
