package com.nci.fogedge.tasks;

import com.nci.fogedge.devices.Device;

/**
 * Represents a computational task in the simulation.
 * Tasks are generated by IoT devices and can be executed on various devices
 * including IoT devices, edge nodes, fog nodes, or cloud datacenters.
 */
public class Task {
    // Task identification
    private String id;
    private Device sourceDevice;
    
    // Task requirements
    private double cpuRequirement; // MIPS
    private double ramRequirement; // MB
    private double storageRequirement; // GB
    private double duration; // seconds
    private double dataInputSize; // KB
    private double dataOutputSize; // KB
    
    // Task timing
    private double creationTime; // simulation time when task was created
    private double submissionTime; // simulation time when task was submitted for execution
    private double startTime; // simulation time when task execution started
    private double finishTime; // simulation time when task execution finished
    
    // Task status
    private TaskStatus status;
    private Device executingDevice;
    private int priority; // 1 (lowest) to 10 (highest)
    private boolean isSecurityCritical;
    
    /**
     * Constructor for a task
     * 
     * @param id Unique identifier for the task
     * @param sourceDevice Device that generated the task
     * @param cpuRequirement CPU requirement in MIPS
     * @param ramRequirement RAM requirement in MB
     * @param storageRequirement Storage requirement in GB
     * @param duration Expected duration in seconds
     * @param creationTime Simulation time when the task was created
     */
    public Task(String id, Device sourceDevice, double cpuRequirement, double ramRequirement,
               double storageRequirement, double duration, double creationTime) {
        this.id = id;
        this.sourceDevice = sourceDevice;
        this.cpuRequirement = cpuRequirement;
        this.ramRequirement = ramRequirement;
        this.storageRequirement = storageRequirement;
        this.duration = duration;
        this.creationTime = creationTime;
        this.dataInputSize = 10.0; // Default input size in KB
        this.dataOutputSize = 5.0; // Default output size in KB
        this.status = TaskStatus.CREATED;
        this.priority = 5; // Default priority (medium)
        this.isSecurityCritical = false;
    }
    
    /**
     * Constructor for a task with all parameters
     * 
     * @param id Unique identifier for the task
     * @param sourceDevice Device that generated the task
     * @param cpuRequirement CPU requirement in MIPS
     * @param ramRequirement RAM requirement in MB
     * @param storageRequirement Storage requirement in GB
     * @param duration Expected duration in seconds
     * @param dataInputSize Input data size in KB
     * @param dataOutputSize Output data size in KB
     * @param creationTime Simulation time when the task was created
     * @param priority Task priority (1-10)
     * @param isSecurityCritical Whether the task is security-critical
     */
    public Task(String id, Device sourceDevice, double cpuRequirement, double ramRequirement,
               double storageRequirement, double duration, double dataInputSize, double dataOutputSize,
               double creationTime, int priority, boolean isSecurityCritical) {
        this.id = id;
        this.sourceDevice = sourceDevice;
        this.cpuRequirement = cpuRequirement;
        this.ramRequirement = ramRequirement;
        this.storageRequirement = storageRequirement;
        this.duration = duration;
        this.dataInputSize = dataInputSize;
        this.dataOutputSize = dataOutputSize;
        this.creationTime = creationTime;
        this.status = TaskStatus.CREATED;
        this.priority = Math.max(1, Math.min(10, priority)); // Ensure priority is between 1 and 10
        this.isSecurityCritical = isSecurityCritical;
    }
    
    /**
     * Submits the task for execution
     * 
     * @param currentTime Current simulation time
     */
    public void submit(double currentTime) {
        this.submissionTime = currentTime;
        this.status = TaskStatus.SUBMITTED;
    }
    
    /**
     * Starts the execution of the task
     * 
     * @param currentTime Current simulation time
     * @param executingDevice Device that is executing the task
     */
    public void start(double currentTime, Device executingDevice) {
        this.startTime = currentTime;
        this.executingDevice = executingDevice;
        this.status = TaskStatus.EXECUTING;
    }
    
    /**
     * Completes the execution of the task
     * 
     * @param currentTime Current simulation time
     */
    public void complete(double currentTime) {
        this.finishTime = currentTime;
        this.status = TaskStatus.COMPLETED;
    }
    
    /**
     * Fails the execution of the task
     * 
     * @param currentTime Current simulation time
     */
    public void fail(double currentTime) {
        this.finishTime = currentTime;
        this.status = TaskStatus.FAILED;
    }
    
    /**
     * Calculates the waiting time of the task
     * 
     * @return Waiting time in seconds
     */
    public double getWaitingTime() {
        if (startTime < 0) {
            return -1; // Task hasn't started yet
        }
        return startTime - submissionTime;
    }
    
    /**
     * Calculates the execution time of the task
     * 
     * @return Execution time in seconds
     */
    public double getExecutionTime() {
        if (finishTime < 0 || startTime < 0) {
            return -1; // Task hasn't finished or started yet
        }
        return finishTime - startTime;
    }
    
    /**
     * Calculates the response time of the task
     * 
     * @return Response time in seconds
     */
    public double getResponseTime() {
        if (finishTime < 0) {
            return -1; // Task hasn't finished yet
        }
        return finishTime - submissionTime;
    }
    
    /**
     * Gets the unique identifier of the task
     * 
     * @return The task ID
     */
    public String getId() {
        return id;
    }
    
    /**
     * Gets the source device of the task
     * 
     * @return The source device
     */
    public Device getSourceDevice() {
        return sourceDevice;
    }
    
    /**
     * Gets the CPU requirement of the task
     * 
     * @return The CPU requirement in MIPS
     */
    public double getCpuRequirement() {
        return cpuRequirement;
    }
    
    /**
     * Gets the RAM requirement of the task
     * 
     * @return The RAM requirement in MB
     */
    public double getRamRequirement() {
        return ramRequirement;
    }
    
    /**
     * Gets the storage requirement of the task
     * 
     * @return The storage requirement in GB
     */
    public double getStorageRequirement() {
        return storageRequirement;
    }
    
    /**
     * Gets the duration of the task
     * 
     * @return The duration in seconds
     */
    public double getDuration() {
        return duration;
    }
    
    /**
     * Gets the input data size of the task
     * 
     * @return The input data size in KB
     */
    public double getDataInputSize() {
        return dataInputSize;
    }
    
    /**
     * Gets the output data size of the task
     * 
     * @return The output data size in KB
     */
    public double getDataOutputSize() {
        return dataOutputSize;
    }
    
    /**
     * Gets the creation time of the task
     * 
     * @return The creation time
     */
    public double getCreationTime() {
        return creationTime;
    }
    
    /**
     * Gets the submission time of the task
     * 
     * @return The submission time
     */
    public double getSubmissionTime() {
        return submissionTime;
    }
    
    /**
     * Gets the start time of the task
     * 
     * @return The start time
     */
    public double getStartTime() {
        return startTime;
    }
    
    /**
     * Gets the finish time of the task
     * 
     * @return The finish time
     */
    public double getFinishTime() {
        return finishTime;
    }
    
    /**
     * Gets the status of the task
     * 
     * @return The task status
     */
    public TaskStatus getStatus() {
        return status;
    }
    
    /**
     * Gets the executing device of the task
     * 
     * @return The executing device
     */
    public Device getExecutingDevice() {
        return executingDevice;
    }
    
    /**
     * Gets the priority of the task
     * 
     * @return The task priority (1-10)
     */
    public int getPriority() {
        return priority;
    }
    
    /**
     * Checks if the task is security-critical
     * 
     * @return True if the task is security-critical, false otherwise
     */
    public boolean isSecurityCritical() {
        return isSecurityCritical;
    }
    
    /**
     * Sets the input data size of the task
     * 
     * @param dataInputSize The input data size in KB
     */
    public void setDataInputSize(double dataInputSize) {
        this.dataInputSize = dataInputSize;
    }
    
    /**
     * Sets the output data size of the task
     * 
     * @param dataOutputSize The output data size in KB
     */
    public void setDataOutputSize(double dataOutputSize) {
        this.dataOutputSize = dataOutputSize;
    }
    
    /**
     * Sets the priority of the task
     * 
     * @param priority The task priority (1-10)
     */
    public void setPriority(int priority) {
        this.priority = Math.max(1, Math.min(10, priority)); // Ensure priority is between 1 and 10
    }
    
    /**
     * Sets whether the task is security-critical
     * 
     * @param securityCritical True if the task is security-critical, false otherwise
     */
    public void setSecurityCritical(boolean securityCritical) {
        this.isSecurityCritical = securityCritical;
    }
    
    /**
     * Returns a string representation of the task
     * 
     * @return String representation of the task
     */
    @Override
    public String toString() {
        return "Task{" +
               "id='" + id + '\'' +
               ", sourceDevice=" + (sourceDevice != null ? sourceDevice.getId() : "null") +
               ", status=" + status +
               ", cpuRequirement=" + cpuRequirement +
               ", ramRequirement=" + ramRequirement +
               ", storageRequirement=" + storageRequirement +
               ", duration=" + duration +
               ", dataInputSize=" + dataInputSize +
               ", dataOutputSize=" + dataOutputSize +
               ", creationTime=" + creationTime +
               ", submissionTime=" + submissionTime +
               ", startTime=" + startTime +
               ", finishTime=" + finishTime +
               ", priority=" + priority +
               ", isSecurityCritical=" + isSecurityCritical +
               '}';
    }
}
