package com.nci.fogedge.tasks;

/**
 * Represents a computational task in the simulation.
 * Tasks are generated by IoT devices and can be executed locally or offloaded
 * to edge nodes, fog nodes, or cloud datacenters.
 */
public class Task {
    // Task properties
    private String id;
    private String sourceDeviceId;
    private int length; // in Million Instructions (MI)
    private int inputSize; // in KB
    private int outputSize; // in KB
    private int creationTick;
    private int startTick;
    private int completionTick;
    private TaskStatus status;
    private String executorDeviceId;
    private TaskType type;
    private int priority; // 1-10, higher means higher priority
    private boolean isSecurityCritical;
    
    /**
     * Constructor for a basic task
     * 
     * @param id Unique identifier for the task
     * @param sourceDeviceId ID of the device that created the task
     * @param length Task length in Million Instructions (MI)
     * @param inputSize Input data size in KB
     * @param outputSize Output data size in KB
     * @param creationTick Simulation tick when the task was created
     */
    public Task(String id, String sourceDeviceId, int length, int inputSize, int outputSize, int creationTick) {
        this.id = id;
        this.sourceDeviceId = sourceDeviceId;
        this.length = length;
        this.inputSize = inputSize;
        this.outputSize = outputSize;
        this.creationTick = creationTick;
        this.status = TaskStatus.CREATED;
        this.type = TaskType.COMPUTATIONAL;
        this.priority = 5; // Default priority
        this.isSecurityCritical = false;
    }
    
    /**
     * Constructor for a detailed task
     * 
     * @param id Unique identifier for the task
     * @param sourceDeviceId ID of the device that created the task
     * @param length Task length in Million Instructions (MI)
     * @param inputSize Input data size in KB
     * @param outputSize Output data size in KB
     * @param creationTick Simulation tick when the task was created
     * @param type Type of the task
     * @param priority Priority of the task (1-10)
     * @param isSecurityCritical Whether the task is security-critical
     */
    public Task(String id, String sourceDeviceId, int length, int inputSize, int outputSize, 
                int creationTick, TaskType type, int priority, boolean isSecurityCritical) {
        this.id = id;
        this.sourceDeviceId = sourceDeviceId;
        this.length = length;
        this.inputSize = inputSize;
        this.outputSize = outputSize;
        this.creationTick = creationTick;
        this.status = TaskStatus.CREATED;
        this.type = type;
        this.priority = Math.max(1, Math.min(10, priority)); // Ensure priority is between 1 and 10
        this.isSecurityCritical = isSecurityCritical;
    }
    
    /**
     * Sets the task status to READY
     */
    public void setReady() {
        this.status = TaskStatus.READY;
    }
    
    /**
     * Sets the task status to RUNNING and records the start tick
     * 
     * @param startTick Simulation tick when the task started running
     * @param executorDeviceId ID of the device executing the task
     */
    public void setRunning(int startTick, String executorDeviceId) {
        this.status = TaskStatus.RUNNING;
        this.startTick = startTick;
        this.executorDeviceId = executorDeviceId;
    }
    
    /**
     * Sets the task status to COMPLETED and records the completion tick
     * 
     * @param completionTick Simulation tick when the task completed
     */
    public void setCompleted(int completionTick) {
        this.status = TaskStatus.COMPLETED;
        this.completionTick = completionTick;
    }
    
    /**
     * Sets the task status to FAILED
     */
    public void setFailed() {
        this.status = TaskStatus.FAILED;
    }
    
    /**
     * Sets the task status to OFFLOADED
     * 
     * @param executorDeviceId ID of the device the task was offloaded to
     */
    public void setOffloaded(String executorDeviceId) {
        this.status = TaskStatus.OFFLOADED;
        this.executorDeviceId = executorDeviceId;
    }
    
    /**
     * Calculates the total execution time of the task
     * 
     * @return Execution time in simulation ticks, or -1 if the task is not completed
     */
    public int getExecutionTime() {
        if (status == TaskStatus.COMPLETED && startTick > 0) {
            return completionTick - startTick;
        }
        return -1;
    }
    
    /**
     * Calculates the total waiting time of the task
     * 
     * @return Waiting time in simulation ticks, or -1 if the task has not started
     */
    public int getWaitingTime() {
        if (startTick > 0) {
            return startTick - creationTick;
        }
        return -1;
    }
    
    /**
     * Calculates the total response time of the task (waiting + execution)
     * 
     * @return Response time in simulation ticks, or -1 if the task is not completed
     */
    public int getResponseTime() {
        if (status == TaskStatus.COMPLETED) {
            return completionTick - creationTick;
        }
        return -1;
    }
    
    /**
     * Creates a copy of this task
     * 
     * @return A new Task object with the same properties
     */
    public Task copy() {
        Task copy = new Task(id + "_copy", sourceDeviceId, length, inputSize, outputSize, creationTick, type, priority, isSecurityCritical);
        copy.status = this.status;
        copy.startTick = this.startTick;
        copy.completionTick = this.completionTick;
        copy.executorDeviceId = this.executorDeviceId;
        return copy;
    }
    
    // Getters and setters
    
    public String getId() {
        return id;
    }
    
    public String getSourceDeviceId() {
        return sourceDeviceId;
    }
    
    public int getLength() {
        return length;
    }
    
    public int getInputSize() {
        return inputSize;
    }
    
    public int getOutputSize() {
        return outputSize;
    }
    
    public int getCreationTick() {
        return creationTick;
    }
    
    public int getStartTick() {
        return startTick;
    }
    
    public int getCompletionTick() {
        return completionTick;
    }
    
    public TaskStatus getStatus() {
        return status;
    }
    
    public String getExecutorDeviceId() {
        return executorDeviceId;
    }
    
    public TaskType getType() {
        return type;
    }
    
    public void setType(TaskType type) {
        this.type = type;
    }
    
    public int getPriority() {
        return priority;
    }
    
    public void setPriority(int priority) {
        this.priority = Math.max(1, Math.min(10, priority));
    }
    
    public boolean isSecurityCritical() {
        return isSecurityCritical;
    }
    
    public void setSecurityCritical(boolean securityCritical) {
        this.isSecurityCritical = securityCritical;
    }
    
    @Override
    public String toString() {
        return "Task{" +
                "id='" + id + '\'' +
                ", sourceDeviceId='" + sourceDeviceId + '\'' +
                ", length=" + length +
                ", inputSize=" + inputSize +
                ", outputSize=" + outputSize +
                ", status=" + status +
                ", type=" + type +
                ", priority=" + priority +
                ", isSecurityCritical=" + isSecurityCritical +
                '}';
    }
}
