package com.fog.eedto.model;

/**
 * Represents a computational task in the EEDTO system.
 * Tasks are generated by IoT devices and can be executed locally or offloaded to edge/cloud.
 */
public class Task {
    private final int id;
    private final long length; // in Million Instructions (MI)
    private final long inputSize; // in bytes
    private final long outputSize; // in bytes
    private final double deadline; // in seconds
    private final double creationTime; // in seconds
    private TaskType type;
    private TaskStatus status;
    private double startTime;
    private double finishTime;
    private double energyConsumed; // in joules
    private DeviceType executionLocation;

    /**
     * Enum representing the type of task based on its computational requirements
     */
    public enum TaskType {
        LIGHTWEIGHT, // Low computational requirements
        MEDIUM,      // Medium computational requirements
        INTENSIVE    // High computational requirements
    }

    /**
     * Enum representing the current status of the task
     */
    public enum TaskStatus {
        CREATED,
        WAITING,
        EXECUTING,
        COMPLETED,
        FAILED,
        OFFLOADED,
        REJECTED
    }

    /**
     * Enum representing where the task is executed
     */
    public enum DeviceType {
        IOT_DEVICE,
        EDGE_SERVER,
        CLOUD_SERVER
    }

    /**
     * Constructor for the Task class
     * 
     * @param id Unique identifier for the task
     * @param length Computational length in Million Instructions (MI)
     * @param inputSize Input data size in bytes
     * @param outputSize Output data size in bytes
     * @param deadline Maximum time allowed for task completion in seconds
     * @param creationTime Time when the task was created in seconds
     * @param type Type of task based on computational requirements
     */
    public Task(int id, long length, long inputSize, long outputSize, double deadline, 
                double creationTime, TaskType type) {
        this.id = id;
        this.length = length;
        this.inputSize = inputSize;
        this.outputSize = outputSize;
        this.deadline = deadline;
        this.creationTime = creationTime;
        this.type = type;
        this.status = TaskStatus.CREATED;
        this.startTime = -1;
        this.finishTime = -1;
        this.energyConsumed = 0;
        this.executionLocation = null;
    }

    // Getters and setters
    public int getId() {
        return id;
    }

    public long getLength() {
        return length;
    }

    public long getInputSize() {
        return inputSize;
    }

    public long getOutputSize() {
        return outputSize;
    }

    public double getDeadline() {
        return deadline;
    }

    public double getArrivalTime() {
        return creationTime;
    }

    public TaskType getTaskType() {
        return type;
    }

    public void setType(TaskType type) {
        this.type = type;
    }

    public TaskStatus getStatus() {
        return status;
    }

    public void setStatus(TaskStatus status) {
        this.status = status;
    }

    public double getStartTime() {
        return startTime;
    }

    public void setStartTime(double startTime) {
        this.startTime = startTime;
    }

    public double getFinishTime() {
        return finishTime;
    }

    public void setFinishTime(double finishTime) {
        this.finishTime = finishTime;
    }

    public double getEnergyConsumed() {
        return energyConsumed;
    }

    public void setEnergyConsumed(double energyConsumed) {
        this.energyConsumed = energyConsumed;
    }

    public DeviceType getExecutionLocation() {
        return executionLocation;
    }

    public void setExecutionLocation(DeviceType executionLocation) {
        this.executionLocation = executionLocation;
    }

    /**
     * Calculate the execution time of the task based on the processing speed
     * 
     * @param mips Processing speed in Million Instructions Per Second
     * @return Execution time in seconds
     */
    public double calculateExecutionTime(double mips) {
        return length / mips;
    }

    /**
     * Calculate the response time (total time from creation to completion)
     * 
     * @return Response time in seconds
     */
    public double calculateResponseTime() {
        if (finishTime < 0) {
            throw new IllegalStateException("Task has not finished yet");
        }
        return finishTime - creationTime;
    }

    /**
     * Check if the task meets its deadline
     * 
     * @return true if the task meets its deadline, false otherwise
     */
    public boolean meetsDeadline() {
        if (finishTime < 0) {
            throw new IllegalStateException("Task has not finished yet");
        }
        return calculateResponseTime() <= deadline;
    }

    @Override
    public String toString() {
        return "Task{" +
                "id=" + id +
                ", length=" + length +
                ", inputSize=" + inputSize +
                ", outputSize=" + outputSize +
                ", deadline=" + deadline +
                ", type=" + type +
                ", status=" + status +
                ", executionLocation=" + executionLocation +
                '}';
    }
}
