package com.nci.fogedge.iot;

import com.nci.fogedge.network.NetworkManager;
import com.nci.fogedge.utils.MetricsCollector;

/**
 * Base interface for all IoT devices in the Fog and Edge Computing System
 * 
 * This interface defines the contract that all IoT devices must implement,
 * including sensors and actuators. It provides methods for device lifecycle
 * management, data generation, and communication with the network layer.
 * 
 * @author National College of Ireland - Fog and Edge Computing Project
 * @version 1.0.0
 * @since 2024
 */
public interface IoTDevice {
    
    /**
     * Get the unique identifier for this device
     * 
     * @return Device ID string
     */
    String getDeviceId();
    
    /**
     * Get the type of this IoT device
     * 
     * @return Device type (e.g., "SENSOR", "ACTUATOR")
     */
    String getDeviceType();
    
    /**
     * Get the current status of the device
     * 
     * @return Device status (e.g., "ACTIVE", "INACTIVE", "ERROR")
     */
    String getStatus();
    
    /**
     * Check if the device is healthy and functioning properly
     * 
     * @return true if device is healthy, false otherwise
     */
    boolean isHealthy();
    
    /**
     * Start the device and begin data generation/processing
     */
    void start();
    
    /**
     * Stop the device and cease all operations
     */
    void stop();
    
    /**
     * Generate sensor data or perform actuator operations
     * 
     * @return Generated data or operation result
     */
    Object generateData();
    
    /**
     * Get the current battery level of the device (if applicable)
     * 
     * @return Battery level as percentage (0-100)
     */
    double getBatteryLevel();
    
    /**
     * Get the signal strength for wireless communication
     * 
     * @return Signal strength in dBm
     */
    double getSignalStrength();
    
    /**
     * Get the data transmission rate of the device
     * 
     * @return Transmission rate in bytes per second
     */
    double getTransmissionRate();
    
    /**
     * Get the total data generated by this device
     * 
     * @return Total data in bytes
     */
    long getTotalDataGenerated();
    
    /**
     * Get the number of successful transmissions
     * 
     * @return Count of successful transmissions
     */
    int getSuccessfulTransmissions();
    
    /**
     * Get the number of failed transmissions
     * 
     * @return Count of failed transmissions
     */
    int getFailedTransmissions();
    
    /**
     * Get the transmission success rate
     * 
     * @return Success rate as percentage (0-100)
     */
    double getTransmissionSuccessRate();
    
    /**
     * Get device configuration parameters
     * 
     * @return Map of configuration parameters
     */
    java.util.Map<String, Object> getConfiguration();
    
    /**
     * Update device configuration
     * 
     * @param config New configuration parameters
     */
    void updateConfiguration(java.util.Map<String, Object> config);
    
    /**
     * Get device performance metrics
     * 
     * @return Map containing performance metrics
     */
    java.util.Map<String, Object> getPerformanceMetrics();
    
    /**
     * Reset device statistics and counters
     */
    void resetStatistics();
    
    /**
     * Perform device self-diagnostic
     * 
     * @return Diagnostic result
     */
    DiagnosticResult performDiagnostic();
    
    /**
     * Result of device diagnostic operation
     */
    class DiagnosticResult {
        private final boolean passed;
        private final String message;
        private final java.util.Map<String, Object> details;
        
        public DiagnosticResult(boolean passed, String message, java.util.Map<String, Object> details) {
            this.passed = passed;
            this.message = message;
            this.details = details;
        }
        
        public boolean isPassed() {
            return passed;
        }
        
        public String getMessage() {
            return message;
        }
        
        public java.util.Map<String, Object> getDetails() {
            return details;
        }
    }
} 