package org.nci.fogedge.security;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.nci.fogedge.security.AttackSimulator.Attack;
import org.nci.fogedge.topology.EdgeNode;
import org.nci.fogedge.topology.FogNode;
import org.nci.fogedge.topology.IoTDevice;
import org.nci.fogedge.topology.NetworkTopology;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

/**
 * Class to manage security measures and countermeasures in the fog and edge computing topology
 * Based on the paper: "An Overview of Fog Computing and Edge Computing Security and Privacy Issues"
 * (Sensors 2021, 21, 8226, https://doi.org/10.3390/s21248226)
 */
public class SecurityManager {
    private static final Logger logger = LogManager.getLogger(SecurityManager.class);
    private static final Random random = new Random();
    
    private NetworkTopology topology;
    private SecurityLevel securityLevel;
    private Map<Integer, List<Attack>> detectedAttacks; // Step -> List of detected attacks
    private Map<Integer, List<Attack>> preventedAttacks; // Step -> List of prevented attacks
    
    // Security metrics
    private int totalDetectedAttacks;
    private int totalPreventedAttacks;
    private double cumulativeSecurityOverhead;
    private double cumulativeEnergyOverhead;
    
    public SecurityManager() {
        this.detectedAttacks = new HashMap<>();
        this.preventedAttacks = new HashMap<>();
        this.totalDetectedAttacks = 0;
        this.totalPreventedAttacks = 0;
        this.cumulativeSecurityOverhead = 0.0;
        this.cumulativeEnergyOverhead = 0.0;
    }
    
    /**
     * Initialize the security manager with the network topology and security level
     * @param topology The network topology
     * @param securityLevel The security level to apply
     */
    public void initialize(NetworkTopology topology, SecurityLevel securityLevel) {
        this.topology = topology;
        this.securityLevel = securityLevel;
        
        logger.info("Security manager initialized with security level: {}", securityLevel);
    }
    
    /**
     * Apply security measures to IoT data
     * @param device The IoT device
     * @param data The data generated by the device
     */
    public void secureIoTData(IoTDevice device, Object data) {
        // Apply security measures based on security level
        double overhead = calculateSecurityOverhead(SecurityLayer.IOT);
        double energyUsed = calculateEnergyOverhead(SecurityLayer.IOT);
        
        // Consume additional battery for security operations
        device.consumeBattery(energyUsed * 0.01);
        
        logger.debug("Applied IoT-level security to device {} with overhead {} ms and energy {} mJ",
                device.getId(), String.format("%.2f", overhead), String.format("%.2f", energyUsed));
        
        // Update cumulative metrics
        cumulativeSecurityOverhead += overhead;
        cumulativeEnergyOverhead += energyUsed;
    }
    
    /**
     * Apply security measures to edge node processing
     * @param edgeNode The edge node
     * @param data The data to process
     */
    public void secureEdgeProcessing(EdgeNode edgeNode, List<Object> data) {
        // Apply security measures based on security level
        double overhead = calculateSecurityOverhead(SecurityLayer.EDGE);
        double energyUsed = calculateEnergyOverhead(SecurityLayer.EDGE);
        
        logger.debug("Applied Edge-level security to node {} with overhead {} ms and energy {} mJ",
                edgeNode.getId(), String.format("%.2f", overhead), String.format("%.2f", energyUsed));
        
        // Update cumulative metrics
        cumulativeSecurityOverhead += overhead;
        cumulativeEnergyOverhead += energyUsed;
    }
    
    /**
     * Apply security measures to fog node processing
     * @param fogNode The fog node
     * @param data The data to process
     */
    public void secureFogProcessing(FogNode fogNode, List<Object> data) {
        // Apply security measures based on security level
        double overhead = calculateSecurityOverhead(SecurityLayer.FOG);
        double energyUsed = calculateEnergyOverhead(SecurityLayer.FOG);
        
        logger.debug("Applied Fog-level security to node {} with overhead {} ms and energy {} mJ",
                fogNode.getId(), String.format("%.2f", overhead), String.format("%.2f", energyUsed));
        
        // Update cumulative metrics
        cumulativeSecurityOverhead += overhead;
        cumulativeEnergyOverhead += energyUsed;
    }
    
    /**
     * Apply countermeasures to active attacks
     * @param activeAttacks List of active attacks
     * @param step Current simulation step
     */
    public void applyCountermeasures(List<Attack> activeAttacks, int step) {
        if (activeAttacks == null || activeAttacks.isEmpty()) {
            logger.debug("No active attacks to counter in step {}", step);
            return;
        }
        
        List<Attack> stepDetectedAttacks = new ArrayList<>();
        List<Attack> stepPreventedAttacks = new ArrayList<>();
        
        for (Attack attack : activeAttacks) {
            // Determine if the attack is detected based on security level
            if (isAttackDetected(attack)) {
                stepDetectedAttacks.add(attack);
                totalDetectedAttacks++;
                
                logger.info("Detected attack: {} in step {}", attack, step);
                
                // Determine if the attack can be prevented
                if (isAttackPrevented(attack)) {
                    stepPreventedAttacks.add(attack);
                    totalPreventedAttacks++;
                    
                    // Restore the compromised component
                    restoreCompromisedComponent(attack);
                    
                    logger.info("Prevented attack: {} in step {}", attack, step);
                } else {
                    logger.warn("Could not prevent detected attack: {} in step {}", attack, step);
                }
            }
        }
        
        // Store detected and prevented attacks for this step
        if (!stepDetectedAttacks.isEmpty()) {
            detectedAttacks.put(step, stepDetectedAttacks);
        }
        
        if (!stepPreventedAttacks.isEmpty()) {
            preventedAttacks.put(step, stepPreventedAttacks);
        }
        
        logger.info("Step {}: Detected {} attacks, prevented {} attacks", 
                step, stepDetectedAttacks.size(), stepPreventedAttacks.size());
    }
    
    /**
     * Determine if an attack is detected based on security level
     * @param attack The attack to check
     * @return true if the attack is detected
     */
    private boolean isAttackDetected(Attack attack) {
        // Base detection probability on security level
        double detectionProbability = securityLevel.getDetectionRate();
        
        // Adjust based on attack type and target
        AttackType attackType = attack.getType();
        SecurityLayer targetLayer = attackType.getTargetLayer();
        
        // Some attacks are easier to detect than others
        switch (attackType) {
            case EDGE_DOS:
            case IOT_BATTERY_DRAINING:
                detectionProbability += 0.2; // Easier to detect
                break;
                
            case NETWORK_EAVESDROPPING:
            case NETWORK_TRAFFIC_ANALYSIS:
                detectionProbability -= 0.2; // Harder to detect
                break;
        }
        
        // Ensure probability is within valid range
        detectionProbability = Math.min(0.95, Math.max(0.05, detectionProbability));
        
        return random.nextDouble() < detectionProbability;
    }
    
    /**
     * Determine if a detected attack can be prevented
     * @param attack The attack to check
     * @return true if the attack can be prevented
     */
    private boolean isAttackPrevented(Attack attack) {
        // Base prevention probability on security level
        double preventionProbability = securityLevel.getDetectionRate() * 0.8;
        
        // Adjust based on attack type
        AttackType attackType = attack.getType();
        
        // Some attacks are easier to prevent than others
        switch (attackType) {
            case EDGE_AUTHENTICATION_BYPASS:
            case IOT_MALWARE_INJECTION:
                preventionProbability -= 0.1; // Harder to prevent
                break;
                
            case EDGE_DOS:
            case NETWORK_ROUTING_ATTACK:
                preventionProbability += 0.1; // Easier to prevent
                break;
        }
        
        // Ensure probability is within valid range
        preventionProbability = Math.min(0.9, Math.max(0.1, preventionProbability));
        
        return random.nextDouble() < preventionProbability;
    }
    
    /**
     * Restore a compromised component after preventing an attack
     * @param attack The attack that was prevented
     */
    private void restoreCompromisedComponent(Attack attack) {
        Object target = attack.getTarget();
        
        if (target instanceof IoTDevice) {
            ((IoTDevice) target).restore();
        } else if (target instanceof EdgeNode) {
            ((EdgeNode) target).restore();
        } else if (target instanceof FogNode) {
            ((FogNode) target).restore();
        }
    }
    
    /**
     * Calculate security overhead for a specific layer
     * @param layer The security layer
     * @return Security overhead in ms
     */
    private double calculateSecurityOverhead(SecurityLayer layer) {
        // Base overhead on security level
        double baseOverhead = securityLevel.getResourceOverhead() * 100.0; // in ms
        
        // Adjust based on layer
        switch (layer) {
            case IOT:
                return baseOverhead * 0.5; // Lower overhead for IoT
            case EDGE:
                return baseOverhead * 1.0; // Standard overhead for Edge
            case FOG:
                return baseOverhead * 1.5; // Higher overhead for Fog
            case NETWORK:
                return baseOverhead * 0.8; // Medium overhead for Network
            default:
                return baseOverhead;
        }
    }
    
    /**
     * Calculate energy overhead for security operations
     * @param layer The security layer
     * @return Energy overhead in mJ
     */
    private double calculateEnergyOverhead(SecurityLayer layer) {
        // Base energy overhead on security level
        double baseEnergy = securityLevel.getResourceOverhead() * 50.0; // in mJ
        
        // Adjust based on layer
        switch (layer) {
            case IOT:
                return baseEnergy * 0.3; // Lower energy for IoT (battery constraints)
            case EDGE:
                return baseEnergy * 1.0; // Standard energy for Edge
            case FOG:
                return baseEnergy * 2.0; // Higher energy for Fog (more complex operations)
            case NETWORK:
                return baseEnergy * 0.5; // Medium energy for Network
            default:
                return baseEnergy;
        }
    }
    
    /**
     * Calculate the current security overhead
     * @return Security overhead in ms
     */
    public double calculateSecurityOverhead() {
        // Calculate average overhead per step
        int totalSteps = detectedAttacks.size() + preventedAttacks.size();
        if (totalSteps == 0) return 0.0;
        
        return cumulativeSecurityOverhead / totalSteps;
    }
    
    /**
     * Calculate the current energy overhead for security
     * @return Energy overhead in mJ
     */
    public double calculateEnergyOverhead() {
        // Calculate average energy overhead per step
        int totalSteps = detectedAttacks.size() + preventedAttacks.size();
        if (totalSteps == 0) return 0.0;
        
        return cumulativeEnergyOverhead / totalSteps;
    }
    
    // Getters
    
    public int getDetectedAttacks() {
        return totalDetectedAttacks;
    }
    
    public int getPreventedAttacks() {
        return totalPreventedAttacks;
    }
    
    public SecurityLevel getSecurityLevel() {
        return securityLevel;
    }
}
